### ISSUE TITLE
[Bug] Text shows through buttons

### ISSUE THREAD

**Issue by ClammyMantis488** [Yanis48/BetterWorldList#1]
![image](https://user-images.githubusercontent.com/25406353/82584952-19259500-9b4a-11ea-868d-e3fb40cd0723.png)
I only had fapi and this mod installed

**Comment by YanisBft** [comment]
In what version does it happen?

**Comment by ClammyMantis488** [comment]
ah my bad it's release 1.0.0 for 1.15.2, lemme quickly test the 20w21a version

**Comment by ClammyMantis488** [comment]
It also happens on 20w21a ![image](https://user-images.githubusercontent.com/25406353/82618547-35e0bd80-9b88-11ea-9b06-60b711b2c2ee.png)

**Comment by YanisBft** [comment]
Alright, I will take a look asap

**Comment by YanisBft** [comment]
It's a vanilla bug fixed in the latest snapshot (20w22a). It means I will release a version on monday for 20w22a, but the bug won't be fixed in 1.15.2

**Comment by YanisBft** [comment]
Fixed in version 1.0.1
