### ISSUE TITLE
crash on clicking on world[1.16-pre7]

### ISSUE THREAD

**Issue by SDUBZ** [Yanis48/BetterWorldList#3]
[crash-2020-06-17_14.01.49-client.txt](https://github.com/Yanis48/BetterWorldList/files/4790288/crash-2020-06-17_14.01.49-client.txt)
[latest.log](https://github.com/Yanis48/BetterWorldList/files/4790289/latest.log)

betterworldlist-1.0.2-1.16-pre2.jar

**Comment by YanisBft** [comment]
Thanks for the report! A new version will be released in a few hours to fix this crash

**Comment by YanisBft** [comment]
Fixed in the latest release :)
